// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 711 06/05/2020)
// Created on Tue Jan 23 18:29:45 2024

cmdfifo cmdfifo_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.wen(wen_sig) ,	// input  wen_sig
	.din(din_sig) ,	// input [WIDTH-1:0] din_sig
	.full(full_sig) ,	// output  full_sig
	.ren(ren_sig) ,	// input  ren_sig
	.valid(valid_sig) ,	// output  valid_sig
	.dout(dout_sig) ,	// output [WIDTH-1:0] dout_sig
	.empty(empty_sig) ,	// output  empty_sig
	.rx_done(rx_done_sig) ,	// output  rx_done_sig
	.tx_done(tx_done_sig) 	// output  tx_done_sig
);

defparam cmdfifo_inst.LENGTH = 256;
defparam cmdfifo_inst.DEPTH = 256;
defparam cmdfifo_inst.WIDTH = 8;
